### ISSUE TITLE
nimble test fails

### ISSUE THREAD

**Issue by timotheecour** [Nycto/DelaunayNim#3]
after fixing unittest in https://github.com/nim-lang/Nim/pull/14676, nimble test fails

before that PR, a `require` failure would show an error but not result in a nonzero exit code:
```
 [OK] Allow edges to be removed
    /Users/timothee/git_clone/nim/temp/DelaunayNim/tests/t_edge.nim(80, 29): Check failed: connections == @[p(4, 5), p(2, 2)]
    connections was @[(x: 2.0, y: 2.0), (x: 4.0, y: 5.0)]
    @[p(4, 5), p(2, 2)] was @[(x: 4.0, y: 5.0), (x: 2.0, y: 2.0)]
   Success: Execution finished
```

**Comment by Nycto** [comment]
Looks like this was just caused by a bad test. Should now be resolved.
